/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ementor;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vincenzo
 */
public class Menu extends javax.swing.JFrame {

    static ArrayList<Aluno> dadosAluno = new ArrayList();
    static ArrayList<Professor> dadosProfessor = new ArrayList();

    public static void dadosAlunos() {
        DefaultTableModel Tabela = (DefaultTableModel) TabelaAlunos.Tabela_Alunos.getModel();
        for (Aluno obj : dadosAluno) {
            Tabela.addRow(new Object[]{obj.nome, obj.CPF,
                obj.data_nascimento,
                obj.telefone,
                obj.getMatricula(),
                obj.getPeriodo()});
        }
    }

    public static void dadosProfessores() {
        DefaultTableModel Tabela = (DefaultTableModel) TabelaProfessores.Tabela_Professores.getModel();
        for (Professor obj : dadosProfessor) {
            Tabela.addRow(new Object[]{obj.nome, obj.CPF,
                obj.data_nascimento,
                obj.telefone,
                obj.getData_admissao(),
                obj.getSalario_bruto(),
                obj.CargoChefia, obj.CargoCoordenador});
        }
    }

    public void niveis() {
        ConexoesMySQL con = new ConexoesMySQL();
        int nivel = con.recuperaNivel();
        if (nivel == 1) {
            BotaoMenuPrincipal.setEnabled(true);
            botaoCadastroNovoUsuario.setEnabled(false);
            botaoCadastroTurma.setEnabled(false);
        } else if (nivel == 2) {
            BotaoMenuPrincipal.setEnabled(true);
            botaoCadastroNovoUsuario.setEnabled(false);
            botaoCadastroTurma.setEnabled(true);
        } else if (nivel == 3) {
            BotaoMenuPrincipal.setEnabled(true);
            botaoCadastroNovoUsuario.setEnabled(true);
            botaoCadastroTurma.setEnabled(true);
        }
    }

    /**
     * Creates new form Cadastre
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BotaoMenuPrincipal = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        botaoCadastroTurma = new javax.swing.JButton();
        botaoCadastroNovoUsuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela de Cadastro");
        setType(java.awt.Window.Type.UTILITY);

        jPanel1.setBackground(new java.awt.Color(50, 178, 195));

        BotaoMenuPrincipal.setBackground(new java.awt.Color(234, 210, 115));
        BotaoMenuPrincipal.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        BotaoMenuPrincipal.setText("Menu Principal");
        BotaoMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoMenuPrincipalActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ementor/logo2_pronta.png"))); // NOI18N

        botaoCadastroTurma.setBackground(new java.awt.Color(234, 210, 115));
        botaoCadastroTurma.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        botaoCadastroTurma.setText("Cadastrar Turma");
        botaoCadastroTurma.setEnabled(false);
        botaoCadastroTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastroTurmaActionPerformed(evt);
            }
        });

        botaoCadastroNovoUsuario.setBackground(new java.awt.Color(234, 210, 115));
        botaoCadastroNovoUsuario.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        botaoCadastroNovoUsuario.setText("Criar Novo Usuário");
        botaoCadastroNovoUsuario.setEnabled(false);
        botaoCadastroNovoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastroNovoUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botaoCadastroNovoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotaoMenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoCadastroTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoCadastroTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(botaoCadastroNovoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotaoMenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCadastroTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastroTurmaActionPerformed
        CadastroTurmas turmas = new CadastroTurmas();
        turmas.setVisible(true);
    }//GEN-LAST:event_botaoCadastroTurmaActionPerformed

    private void BotaoMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoMenuPrincipalActionPerformed
        Cadastre newCadastro = new Cadastre();
        newCadastro.setVisible(true);
        newCadastro.niveis();
    }//GEN-LAST:event_BotaoMenuPrincipalActionPerformed

    private void botaoCadastroNovoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastroNovoUsuarioActionPerformed
        Usuarios newUsuario = new Usuarios();
        newUsuario.setVisible(true);
    }//GEN-LAST:event_botaoCadastroNovoUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoMenuPrincipal;
    private javax.swing.JButton botaoCadastroNovoUsuario;
    private javax.swing.JButton botaoCadastroTurma;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
