package ementor;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Vincenzo
 */
public class TabelaAlunos extends javax.swing.JFrame {
    
    /**
     * Creates new form TabelaAlunos
     */
    public TabelaAlunos() {
        initComponents();
    }
    
    public void niveis() {
        ConexoesMySQL con = new ConexoesMySQL();
        int nivel = con.recuperaNivel();
        if (nivel == 1) {
            botaoCadastrarNotas.setEnabled(false);
        } else if (nivel == 2) {
            botaoCadastrarNotas.setEnabled(true);
        } else if (nivel == 3) {
            botaoCadastrarNotas.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela_Alunos = new javax.swing.JTable();
        ExibirNotas = new javax.swing.JButton();
        MatriculaAluno = new javax.swing.JTextField();
        botaoCadastrarNotas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        botaoConsultarTurmas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dados dos Alunos");
        setType(java.awt.Window.Type.UTILITY);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Tabela_Alunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome do Aluno", "CPF", "Data de Nascimento", "Telefone", "Matrícula", "Período"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabela_Alunos);

        ExibirNotas.setText("Consultar notas");
        ExibirNotas.setToolTipText("");
        ExibirNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExibirNotasActionPerformed(evt);
            }
        });

        botaoCadastrarNotas.setText("Cadastrar notas");
        botaoCadastrarNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarNotasActionPerformed(evt);
            }
        });

        jLabel1.setText("CPF");

        botaoConsultarTurmas.setText("Consultar Turmas");
        botaoConsultarTurmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConsultarTurmasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(MatriculaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExibirNotas, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(botaoConsultarTurmas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoCadastrarNotas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MatriculaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ExibirNotas)
                .addGap(18, 18, 18)
                .addComponent(botaoCadastrarNotas)
                .addGap(26, 26, 26)
                .addComponent(botaoConsultarTurmas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        niveis();
        ArrayList<Aluno> ListaAlunos = new ArrayList();

        ConexoesMySQL conec = new ConexoesMySQL();
        ListaAlunos = conec.recuperaDadosAlunoDoMySQL("Nome");

        DefaultTableModel Tabela = (DefaultTableModel) TabelaAlunos.Tabela_Alunos.getModel();
        for (Aluno obj : ListaAlunos) {
            Tabela.addRow(new Object[]{obj.nome, obj.CPF,
                obj.data_nascimento,
                obj.telefone,
                obj.getMatricula(),
                obj.getPeriodo()});
        }
    }//GEN-LAST:event_formWindowOpened

    private void ExibirNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExibirNotasActionPerformed
        ConexoesMySQL conec = new ConexoesMySQL();
        Aluno aluno = null;
        String matricula = "";
        String cpf = MatriculaAluno.getText();
        if (cpf != "") {
            aluno = conec.buscaAluno(cpf);
            matricula = aluno.getMatricula() + "";
            ExibirNotas.setEnabled(true);
        }

        if (aluno == null) {
            JOptionPane.showMessageDialog(null, "Aluno não encontrado!", "ERRO", JOptionPane.ERROR_MESSAGE);
        } else {
            ArrayList<Notas> notas = new ArrayList();
            notas = conec.recuperaNotasAlunoDoMySQL(matricula);
           
            TabelaNotas tabela = new TabelaNotas();
            tabela.preencherTabelaNotas(notas);
            tabela.setVisible(true);
        }
    }//GEN-LAST:event_ExibirNotasActionPerformed

    private void botaoCadastrarNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarNotasActionPerformed
        CadastroNotas newNotas = new CadastroNotas();
        newNotas.setVisible(true);
    }//GEN-LAST:event_botaoCadastrarNotasActionPerformed

    private void botaoConsultarTurmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConsultarTurmasActionPerformed
        TabelaTurmas turma = new TabelaTurmas();
        turma.setVisible(true);
    }//GEN-LAST:event_botaoConsultarTurmasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TabelaAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TabelaAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TabelaAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TabelaAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TabelaAlunos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExibirNotas;
    private javax.swing.JTextField MatriculaAluno;
    public static javax.swing.JTable Tabela_Alunos;
    private javax.swing.JButton botaoCadastrarNotas;
    private javax.swing.JButton botaoConsultarTurmas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
